// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Munkabeosztas_ASP_NET_Core.Data;

namespace Munkabeosztas_ASP_NET_Core.Migrations
{
    [DbContext(typeof(MunkabeosztasDbContext))]
    partial class MunkabeosztasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Munkabeosztas_ASP_NET_Core.Models.Adminuser", b =>
                {
                    b.Property<int>("AdminuserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AdminuserId");

                    b.ToTable("Adminusers");
                });

            modelBuilder.Entity("Munkabeosztas_ASP_NET_Core.Models.Dolgozo", b =>
                {
                    b.Property<int>("DolgozoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Csaladnev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keresztnev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DolgozoId");

                    b.ToTable("Dolgozok");
                });

            modelBuilder.Entity("Munkabeosztas_ASP_NET_Core.Models.DolgozoMunka", b =>
                {
                    b.Property<int>("DolgozoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MunkaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DolgozoId", "MunkaId");

                    b.HasIndex("MunkaId");

                    b.ToTable("DolgozoMunkak");
                });

            modelBuilder.Entity("Munkabeosztas_ASP_NET_Core.Models.Gepjarmu", b =>
                {
                    b.Property<int>("GepjarmuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rendszam")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(7);

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GepjarmuId");

                    b.ToTable("Gepjarmuvek");
                });

            modelBuilder.Entity("Munkabeosztas_ASP_NET_Core.Models.Munka", b =>
                {
                    b.Property<int>("MunkaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Datum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GepjarmuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Helyszin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MunkaId");

                    b.HasIndex("GepjarmuId");

                    b.ToTable("Munkak");
                });

            modelBuilder.Entity("Munkabeosztas_ASP_NET_Core.Models.DolgozoMunka", b =>
                {
                    b.HasOne("Munkabeosztas_ASP_NET_Core.Models.Dolgozo", "Dolgozo")
                        .WithMany("DolgozoMunkak")
                        .HasForeignKey("DolgozoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Munkabeosztas_ASP_NET_Core.Models.Munka", "Munka")
                        .WithMany("DolgozoMunkak")
                        .HasForeignKey("MunkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Munkabeosztas_ASP_NET_Core.Models.Munka", b =>
                {
                    b.HasOne("Munkabeosztas_ASP_NET_Core.Models.Gepjarmu", "Gepjarmu")
                        .WithMany("Munkak")
                        .HasForeignKey("GepjarmuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
